[workspace]
resolver = "2"
members = [
  "programs/ballista",
  "clients/rust",
  "common",
]
exclude = ["tests/ballista"]
default-members = [
  "programs/ballista",
  "clients/rust",
  "common",
]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/Jac0xb/ballista"
repository = "https://github.com/Jac0xb/ballista"
readme = "./README.md"
keywords = ["solana", "svm", "transactions"]

[workspace.dependencies]
pinocchio = { version = "=0.11.2", features = ["cpi"] }
pinocchio-system = "=0.6.1"
solana-address = { version = "=2.7.0", features = ["curve25519", "decode"] }
solana-sha256-hasher = { version = "=3.1.0", features = ["sha2"] }
zerocopy = { version = "=0.8.56", features = ["derive"] }

[profile.release]
lto = "fat"
overflow-checks = true
