[package]
name = "ballista"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Reusable instruction templates for the SVM"
authors = ["Jac0xb"]
readme = "../../README.md"

[lib]
name = "ballista"
crate-type = ["cdylib"]

[features]
default = []
no-entrypoint = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }

[dependencies]
thiserror = "=1.0.69"
ballista-common = { path = "../../common" }
pinocchio = { workspace = true }
pinocchio-system = { workspace = true }
solana-address = { workspace = true }
solana-sha256-hasher = { workspace = true }
