[package]
name = "ballista-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "A rust client for Ballista"

[lib]
crate-type = ["lib"]

[features]
default = []

[dependencies]
solana-program = "=4.1.0"
solana-sha256-hasher = { workspace = true }
ballista-common = { path = "../../common" }
