[package]
name = "ballista-common"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Shared common library used in ballista protocol and sdk"

[lib]
crate-type = ["lib"]

[dependencies]
zerocopy = { workspace = true }
